// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {releaserdto} from '../models';
import {context} from '../models';
import {updaterdto} from '../models';

export function CheckForUpdate():Promise<releaserdto.ReleaseAsset>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartUpdate():Promise<void>;

export function UpdaterStateGet():Promise<updaterdto.UpdaterState>;
