version: "3"

tasks:
  default:
    desc: Show available commands
    cmds:
      - task --list

  generate:
    desc: Build artefacts for the demonstration (dispatches based on host OS/arch)
    silent: true
    cmds:
      - task: generate:mac
      - task: generate:linux:amd64
      - task: generate:linux:arm64

  generate:mac:
    desc: Generate artefacts on macOS host
    platforms: [darwin]
    cmds:
      - echo "--- Generating example artefacts ---"
      - echo "Building v1 native in current folder"
      - wails build -ldflags="-s -w -X main.BuildID=1.0.0"
      - rm -rf ./wails-app.app
      - mv ./build/bin/wails-app.app ./wails-app.app

      - echo "Building v2 darwin builds for update test"
      - task: wails:build:tar:darwin
        vars: { GOARCH: amd64, VERSION: "2.0.0" }
      - task: wails:build:tar:darwin
        vars: { GOARCH: arm64, VERSION: "2.0.0" }

      - go run cmd/prepare_assets.go 2.0.0

  generate:linux:amd64:
    desc: Generate artefacts on Linux x86_64/amd64 host
    platforms: [linux]
    status:
      - '[ "$(uname -m)" = "x86_64" ] || [ "$(uname -m)" = "amd64" ]'
    cmds:
      - echo "--- Generating example artefacts ---"
      - echo "Building v1 native in current folder"
      - wails build -ldflags="-s -w -X main.BuildID=1.0.0" --tags "webkit2_41"
      - rm -rf ./wails-app
      - mv ./build/bin/wails-app ./wails-app

      - echo "Building v2 linux builds for update test"
      - GOOS=linux GOARCH=amd64 wails build -ldflags="-s -w -X main.BuildID=2.0.0" --tags "webkit2_41"
      - mv ./build/bin/wails-app ./assets/wails-app-linux-amd64-webkit241
      - go run cmd/prepare_assets.go 2.0.0

  generate:linux:arm64:
    desc: Generate artefacts on Linux arm64/aarch64 host
    platforms: [linux]
    status:
      - '[ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ]'
    cmds:
      - echo "--- Generating example artefacts ---"
      - echo "Building v1 native in current folder"
      - wails build -ldflags="-s -w -X main.BuildID=1.0.0 -X main.Variant=webkit241" --tags "webkit2_41"
      - rm -rf ./wails-app
      - mv ./build/bin/wails-app ./wails-app

      - echo "Building v2 linux builds for update test"
      - GOOS=linux GOARCH=arm64 wails build -ldflags="-s -w -X main.BuildID=2.0.0 -X main.Variant=webkit241" --tags "webkit2_41"
      - mv ./build/bin/wails-app ./assets/wails-app-linux-arm64-webkit241
      - go run cmd/prepare_assets.go 2.0.0

  wails:build:tar:darwin:
    internal: true
    requires:
      vars: [GOARCH, VERSION]
    env:
      GOOS: darwin
      GOARCH: "{{.GOARCH}}"
    cmds:
      - wails build -ldflags="-s -w -X main.BuildID={{.VERSION}}"
      - tar -cpzf "./wails-app-darwin-{{.GOARCH}}.tar.gz" -C ./build/bin wails-app.app
      - mv "./wails-app-darwin-{{.GOARCH}}.tar.gz" "./assets/wails-app-darwin-{{.GOARCH}}.tar.gz"
      - rm -rf ./build/bin