// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['UpdaterInterface']['CheckForUpdate']();
}

export function SetContext(arg1) {
  return window['go']['main']['UpdaterInterface']['SetContext'](arg1);
}

export function StartUpdate() {
  return window['go']['main']['UpdaterInterface']['StartUpdate']();
}

export function UpdaterStateGet() {
  return window['go']['main']['UpdaterInterface']['UpdaterStateGet']();
}
