// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relaydto

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventInterface creates a new instance of MockEventInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventInterface {
	mock := &MockEventInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventInterface is an autogenerated mock type for the RelayEventInterface type
type MockEventInterface struct {
	mock.Mock
}

type MockEventInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventInterface) EXPECT() *MockEventInterface_Expecter {
	return &MockEventInterface_Expecter{mock: &_m.Mock}
}

// GetRef provides a mock function for the type MockEventInterface
func (_mock *MockEventInterface) GetRef() EventRef {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RelayType")
	}

	var r0 EventRef
	if returnFunc, ok := ret.Get(0).(func() EventRef); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(EventRef)
	}
	return r0
}

// MockEventInterface_GetRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayType'
type MockEventInterface_GetRef_Call struct {
	*mock.Call
}

// GetRef is a helper method to define mock.On call
func (_e *MockEventInterface_Expecter) GetRef() *MockEventInterface_GetRef_Call {
	return &MockEventInterface_GetRef_Call{Call: _e.mock.On("RelayType")}
}

func (_c *MockEventInterface_GetRef_Call) Run(run func()) *MockEventInterface_GetRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventInterface_GetRef_Call) Return(eventRef EventRef) *MockEventInterface_GetRef_Call {
	_c.Call.Return(eventRef)
	return _c
}

func (_c *MockEventInterface_GetRef_Call) RunAndReturn(run func() EventRef) *MockEventInterface_GetRef_Call {
	_c.Call.Return(run)
	return _c
}

// ToZap provides a mock function for the type MockEventInterface
func (_mock *MockEventInterface) ToSlog() []slog.Attr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSlog")
	}

	var r0 []slog.Attr
	if returnFunc, ok := ret.Get(0).(func() []slog.Attr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]slog.Attr)
		}
	}
	return r0
}

// MockEventInterface_ToZap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSlog'
type MockEventInterface_ToZap_Call struct {
	*mock.Call
}

// ToZap is a helper method to define mock.On call
func (_e *MockEventInterface_Expecter) ToZap() *MockEventInterface_ToZap_Call {
	return &MockEventInterface_ToZap_Call{Call: _e.mock.On("ToSlog")}
}

func (_c *MockEventInterface_ToZap_Call) Run(run func()) *MockEventInterface_ToZap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventInterface_ToZap_Call) Return(vs []slog.Attr) *MockEventInterface_ToZap_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockEventInterface_ToZap_Call) RunAndReturn(run func() []slog.Attr) *MockEventInterface_ToZap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelayInterface creates a new instance of MockRelayInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayInterface {
	mock := &MockRelayInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelayInterface is an autogenerated mock type for the RelayInterface type
type MockRelayInterface struct {
	mock.Mock
}

type MockRelayInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayInterface) EXPECT() *MockRelayInterface_Expecter {
	return &MockRelayInterface_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Debug(data RelayEventInterface) {
	_mock.Called(data)
	return
}

// MockRelayInterface_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockRelayInterface_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - data
func (_e *MockRelayInterface_Expecter) Debug(data interface{}) *MockRelayInterface_Debug_Call {
	return &MockRelayInterface_Debug_Call{Call: _e.mock.On("Debug", data)}
}

func (_c *MockRelayInterface_Debug_Call) Run(run func(data RelayEventInterface)) *MockRelayInterface_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RelayEventInterface))
	})
	return _c
}

func (_c *MockRelayInterface_Debug_Call) Return() *MockRelayInterface_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRelayInterface_Debug_Call) RunAndReturn(run func(data RelayEventInterface)) *MockRelayInterface_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Error(data RelayEventInterface) {
	_mock.Called(data)
	return
}

// MockRelayInterface_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockRelayInterface_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - data
func (_e *MockRelayInterface_Expecter) Error(data interface{}) *MockRelayInterface_Error_Call {
	return &MockRelayInterface_Error_Call{Call: _e.mock.On("Error", data)}
}

func (_c *MockRelayInterface_Error_Call) Run(run func(data RelayEventInterface)) *MockRelayInterface_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RelayEventInterface))
	})
	return _c
}

func (_c *MockRelayInterface_Error_Call) Return() *MockRelayInterface_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRelayInterface_Error_Call) RunAndReturn(run func(data RelayEventInterface)) *MockRelayInterface_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Fatal(data RelayEventInterface) {
	_mock.Called(data)
	return
}

// MockRelayInterface_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockRelayInterface_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - data
func (_e *MockRelayInterface_Expecter) Fatal(data interface{}) *MockRelayInterface_Fatal_Call {
	return &MockRelayInterface_Fatal_Call{Call: _e.mock.On("Fatal", data)}
}

func (_c *MockRelayInterface_Fatal_Call) Run(run func(data RelayEventInterface)) *MockRelayInterface_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RelayEventInterface))
	})
	return _c
}

func (_c *MockRelayInterface_Fatal_Call) Return() *MockRelayInterface_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRelayInterface_Fatal_Call) RunAndReturn(run func(data RelayEventInterface)) *MockRelayInterface_Fatal_Call {
	_c.Run(run)
	return _c
}

// Hydrate provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Hydrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hydrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelayInterface_Hydrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hydrate'
type MockRelayInterface_Hydrate_Call struct {
	*mock.Call
}

// Hydrate is a helper method to define mock.On call
func (_e *MockRelayInterface_Expecter) Hydrate() *MockRelayInterface_Hydrate_Call {
	return &MockRelayInterface_Hydrate_Call{Call: _e.mock.On("Hydrate")}
}

func (_c *MockRelayInterface_Hydrate_Call) Run(run func()) *MockRelayInterface_Hydrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelayInterface_Hydrate_Call) Return(err error) *MockRelayInterface_Hydrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelayInterface_Hydrate_Call) RunAndReturn(run func() error) *MockRelayInterface_Hydrate_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Info(data RelayEventInterface) {
	_mock.Called(data)
	return
}

// MockRelayInterface_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockRelayInterface_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - data
func (_e *MockRelayInterface_Expecter) Info(data interface{}) *MockRelayInterface_Info_Call {
	return &MockRelayInterface_Info_Call{Call: _e.mock.On("Info", data)}
}

func (_c *MockRelayInterface_Info_Call) Run(run func(data RelayEventInterface)) *MockRelayInterface_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RelayEventInterface))
	})
	return _c
}

func (_c *MockRelayInterface_Info_Call) Return() *MockRelayInterface_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRelayInterface_Info_Call) RunAndReturn(run func(data RelayEventInterface)) *MockRelayInterface_Info_Call {
	_c.Run(run)
	return _c
}

// StreamAll provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) StreamAll() <-chan Event {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StreamAll")
	}

	var r0 <-chan Event
	if returnFunc, ok := ret.Get(0).(func() <-chan Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Event)
		}
	}
	return r0
}

// MockRelayInterface_StreamAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamAll'
type MockRelayInterface_StreamAll_Call struct {
	*mock.Call
}

// StreamAll is a helper method to define mock.On call
func (_e *MockRelayInterface_Expecter) StreamAll() *MockRelayInterface_StreamAll_Call {
	return &MockRelayInterface_StreamAll_Call{Call: _e.mock.On("StreamAll")}
}

func (_c *MockRelayInterface_StreamAll_Call) Run(run func()) *MockRelayInterface_StreamAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelayInterface_StreamAll_Call) Return(eventCh <-chan Event) *MockRelayInterface_StreamAll_Call {
	_c.Call.Return(eventCh)
	return _c
}

func (_c *MockRelayInterface_StreamAll_Call) RunAndReturn(run func() <-chan Event) *MockRelayInterface_StreamAll_Call {
	_c.Call.Return(run)
	return _c
}

// StreamKey provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) StreamKey(key EventRef) <-chan Event {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for StreamKey")
	}

	var r0 <-chan Event
	if returnFunc, ok := ret.Get(0).(func(EventRef) <-chan Event); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Event)
		}
	}
	return r0
}

// MockRelayInterface_StreamKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamKey'
type MockRelayInterface_StreamKey_Call struct {
	*mock.Call
}

// StreamKey is a helper method to define mock.On call
//   - key
func (_e *MockRelayInterface_Expecter) StreamKey(key interface{}) *MockRelayInterface_StreamKey_Call {
	return &MockRelayInterface_StreamKey_Call{Call: _e.mock.On("StreamKey", key)}
}

func (_c *MockRelayInterface_StreamKey_Call) Run(run func(key EventRef)) *MockRelayInterface_StreamKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(EventRef))
	})
	return _c
}

func (_c *MockRelayInterface_StreamKey_Call) Return(eventCh <-chan Event) *MockRelayInterface_StreamKey_Call {
	_c.Call.Return(eventCh)
	return _c
}

func (_c *MockRelayInterface_StreamKey_Call) RunAndReturn(run func(key EventRef) <-chan Event) *MockRelayInterface_StreamKey_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function for the type MockRelayInterface
func (_mock *MockRelayInterface) Warn(data RelayEventInterface) {
	_mock.Called(data)
	return
}

// MockRelayInterface_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockRelayInterface_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - data
func (_e *MockRelayInterface_Expecter) Warn(data interface{}) *MockRelayInterface_Warn_Call {
	return &MockRelayInterface_Warn_Call{Call: _e.mock.On("Warn", data)}
}

func (_c *MockRelayInterface_Warn_Call) Run(run func(data RelayEventInterface)) *MockRelayInterface_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RelayEventInterface))
	})
	return _c
}

func (_c *MockRelayInterface_Warn_Call) Return() *MockRelayInterface_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRelayInterface_Warn_Call) RunAndReturn(run func(data RelayEventInterface)) *MockRelayInterface_Warn_Call {
	_c.Run(run)
	return _c
}
